version: '3.4'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    stdin_open: true
    ports:
      - 5432:5432
    networks:
      - uni-auto
  api-dev:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    depends_on:
      - postgres
    ports:
      - 3001:3001
    command: [sh, -c, 'npm run start:dev']
    volumes:
      - ./apps/api:/app:delegated
      - /app/node_modules
    networks:
      - uni-auto
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: prod
    working_dir: /app/dist
    ports:
      - 8765:3001
    networks:
      - uni-auto
  cron:
    build:
      context: ./apps/cron
      dockerfile: Dockerfile
      target: prod
    working_dir: /app/dist
    deploy:
      replicas: 3
    networks:
      - uni-auto

networks:
  uni-auto:
    driver: bridge
