version: '3.4'

services:
  api:
    image: uni-auto/api:latest
    restart: always
    networks:
      - postgres
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`uni.nirewen.dev`) && PathPrefix(`/api`)'
      - 'traefik.http.routers.api.entrypoints=https'
      - 'traefik.http.routers.api.tls=true'
      - 'traefik.http.services.api.loadbalancer.server.port=3000'

  cron:
    image: uni-auto/cron:latest
    restart: always
    deploy:
      replicas: 3
    networks:
      - postgres

  web:
    image: uni-auto/web:latest
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.web.rule=Host(`uni.nirewen.dev`)'
      - 'traefik.http.routers.web.entrypoints=https'
      - 'traefik.http.routers.web.tls=true'
      - 'traefik.http.services.web.loadbalancer.server.port=3000'
    networks:
      - proxy

networks:
  postgres:
    external: true
  proxy:
    external: true
