version: '3.4'

services:
  api-dev:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    ports:
      - 3001:3001
    command: [sh, -c, 'npm run start:dev']
    volumes:
      - ./apps/api:/app:delegated
      - /app/node_modules
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: prod
    ports:
      - 3001:3001
    volumes:
      - /app/node_modules
