version: '3.4'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    stdin_open: true
    ports:
      - 5432:5432
    networks:
      - uni-auto

  api:
    image: uni-auto/api:latest
    restart: always
    ports:
      - 8765:3000
    networks:
      - uni-auto

  cron:
    image: uni-auto/cron:latest
    restart: always
    deploy:
      replicas: 3
    networks:
      - uni-auto

  web:
    image: uni-auto/web:latest
    restart: always
    ports:
      - 8764:3000
    networks:
      - uni-auto

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/dozzle/data:/data
    environment:
      DOZZLE_AUTH_PROVIDER: simple
    ports:
      - 9999:8080

networks:
  uni-auto:
    driver: bridge
